# Generated by Django 5.0.6 on 2024-06-27 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_section_article_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='articles', to='webapp.section', verbose_name='Секция'),
        ),
    ]
