# Generated by Django 5.0.6 on 2024-07-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_article_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
