# Generated by Django 5.0.6 on 2024-07-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_tag_articletag_article_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='tags_old',
        ),
    ]
