# Generated by Django 5.0.6 on 2024-07-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20240710_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags_old',
        ),
        migrations.DeleteModel(
            name='ArticleTag',
        ),
    ]
