# Generated by Django 5.0.6 on 2024-07-10 13:38

from django.db import migrations


def recurce_delete(Tag):
    for tag in Tag.objects.all():
        duplicate_tags = Tag.objects.filter(name=tag.name).exclude(id=tag.id)
        for duplicate_tag in duplicate_tags:
            for article in duplicate_tag.articles.all():
                article.tags.add(tag)
                article.tags.remove(duplicate_tag)
            duplicate_tag.delete()
        if duplicate_tags:
            return recurce_delete(Tag)


def delete_tags_duplicate(apps, schema_editor):
    Tag = apps.get_model('webapp.Tag')
    recurce_delete(Tag)


class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0008_remove_article_tags_old_delete_articletag'),
    ]

    operations = [
        migrations.RunPython(delete_tags_duplicate, migrations.RunPython.noop)
    ]
