# Generated by Django 5.0.6 on 2024-11-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_rename_my_tags_article_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('change_article_status', 'менять статус статье')], 'verbose_name': 'models.article.verbose_name: verbose_name', 'verbose_name_plural': 'models.article.verbose_name_plural: verbose_name_plural'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='models.article.title: content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('new', 'models.article.statuses: new'), ('moderated', 'models.article.statuses: moderated'), ('deleted', 'models.article.statuses: deleted')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=50, verbose_name='models.article.title: title'),
        ),
    ]
