# Generated by Django 5.0.6 on 2024-07-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20240710_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=31, unique=True, verbose_name='Тег'),
        ),
    ]
