# Generated by Django 5.0.6 on 2024-11-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_alter_article_options_alter_article_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='models.article.title: title'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='models.article.title: title'),
        ),
    ]
