name: Django CI

on: workflow_dispatch

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Add environ
        run: cp .env.test ./source/.env

      - name: Run Tests
        run: |
          docker compose run -T --rm web bash -c "/code/manage.py test"